version: "3"
services:
        app:
                container_name: app
                build: ./app
                ports:
                        - "80:80"
                        - "443:443"
                        - "3000:3000"
                links:
                        - node
                        - mongo
        node:
                container_name: node
                build: ./node
                volumes:
                        - ./volumes/bulwark:/root/.bulwark
                ports:
                        - "52543:52543"
                        - "52544:52544"
        mongo:
                container_name: mongo
                image: mongo:3.6-jessie
                volumes:
                        - ./volumes/data:/data/db
                ports:
                        - "27017:27017"
