version: "2"
services:
        blockex:
                container_name: blockex
                restart: always
                build: .
                ports:
                        - "3000:3000"
                links:
                        - bwk
                        - mongo
        bwk:
                container_name: bwk
                restart: always
                build: .
                volumes:
                        - ./bulwark:/root/.bulwark
                ports:
                        - "52544:52544"
        mongo:
                container_name: mongo
                restart: always
                build: .
                volumes:
                        - ./data:/data/db
                ports:
                        - "27017:27017"
        nginx:
                container_name: nginx
                restart: always
                build: .
                volumes:
                        - ./nginx:/etc/nginx
                        - ./ssl:/etc/letsencrypt/
                ports:
                        - "80:80"
                        - "443:443"
                links:
                        - blockex
