version: "3"
services:
        app:
                build: ./app
                ports:
                        - "80:80"
                        - "443:443"
                        - "3000:3000"
                links:
                        - node
                        - mongo
                env_file:
                        - ./.env
        node:
                build: ./node
                volumes:
                        - ./volumes/bulwark:/root/.bulwark
                ports:
                        - "52543:52543"
                        - "52544:52544"
                env_file:
                        - ./.env
        mongo:
                image: mongo
                volumes:
                        - ./volumes/data:/data/db
                ports:
                        - "27017:27017"
                env_file:
                        - ./.env
