version: "2"
services:
        blockex:
                container_name: blockex
                restart: always
                build: .
                ports:
                        - "80:80"
                        - "443:443"
                        - "3000:3000"
                        - "27017:27017"
                        - "52544:52544"
                volumes:
                        - ./bulwark:/root/.bulwark
                        - ./data:/data/db
                        - ./nginx:/etc/nginx
                        - ./letsencrypt:/etc/letsencrypt/
